services:
  postgres:
    image: postgres:15
    container_name: nestjs_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: mydata
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build: .
    container_name: nestjs_app
    restart: always
    depends_on:
      - postgres
    ports:
      - '3000:3000'
    environment:
      DATABASE_URL: 'postgresql://postgres:12345@postgres:5432/mydata'
    command: ['npm', 'run', 'start:migrate:prod']

volumes:
  pgdata:
